---
- name: Directory structure playbook for DC4
  hosts: setup
  become: true

  tasks:
    - name: Log in to server
      ansible.builtin.shell: "ssh root@10.10.84.26 -p 3535"
      become_user: root

    - name: Check if directory exists
      ansible.builtin.stat:
        path: "/apps/puppetmaster/code/environments/production/modules/filemanager/files/nginx/{{ desired_hostname }}"
      register: nginx_dir
      failed_when: false

    - name: Check if directory exists
      ansible.builtin.stat:
        path: "/apps/puppetmaster/code/environments/production/modules/filemanager/files/apache/{{ desired_hostname }}"
      register: apache_dir
      failed_when: false

    - name: Check if directory exists
      ansible.builtin.stat:
        path: "/apps/puppetmaster/code/environments/production/modules/filemanager/files/pbis/{{ desired_hostname }}"
      register: pbis_dir
      failed_when: false

    - name: Exit if directory exists
      ansible.builtin.fail:
        msg: "Directory already exists, exiting."
      when: nginx_dir.stat.exists or apache_dir.stat.exists or pbis_dir.stat.exists

    - name: Run create_puppet_dirs.sh with expect
      ansible.builtin.expect:
        command: "/apps/puppetmaster/code/environments/production/create_puppet_dirs.sh"
        responses:
          Enter\ username\ :\ : "{{ username }}\n"
          Enter\ hostname\ :\ : "{{ desired_hostname }}\n"
      args:
        chdir: "/apps/puppetmaster/code/environments/production"
