---
- name: Run multiple playbooks from os-installation repository
  hosts: setup
  become: true

  tasks:
    - name: Clone os-installation repository
      git:
        repo: https://github.com/ITOpsSupport/os-installation.git
        dest: /opt/os-installation
        version: main

    - name: Run hostname.yaml playbook
      ansible-playbook:
        playbook: /opt/os-installation/hostname.yaml

    - name: Run network1.yaml playbook
      ansible-playbook:
        playbook: /opt/os-installation/network1.yaml

    - name: Run puppet1.yaml playbook
      ansible-playbook:
        playbook: /opt/os-installation/puppet1.yaml

    - name: Run ad_dnsmasq.yaml playbook
      ansible-playbook:
        playbook: /opt/os-installation/ad_dnsmasq.yaml
